config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'changeslog', to: 'static_pages#changeslog'
  get 'help', to: 'static_pages#help'
  get 'feedback', to: 'static_pages#feedback'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :locales, only: [:new]


  get 'documents/delete'
  get '/projects/archive'
  get '/projects/show_archive'
  get "portfolios/watch" => 'portfolios#watch', :as => :watch
  get 'projects/accept' => 'projects#accept', :as => :accept
  get 'projects/refuse' => 'projects#refuse', :as => :refuse
  get 'projects/completed' => 'projects#completed', :as => :completed
  get 'projects/accept_intro' => 'projects#accept_intro', :as => :accept_intro
  get 'projects/intro' => 'projects#intro', :as => :intro

  resources :freelancers
  resources :projects do
    resources :responses, expect: :index
  end
  resources :project do
    resources :comments
  end
  resources :responses do
    resources :comments
  end

  resources :intros
  resources :documents
  resources :photos
  resources :portfolios
  resources :backgrounds
  resources :project_transitions
  namespace :project do
    get 'my/tasks', to: 'profile_projects#index', as: :user_projects
  end
  resources :subscribers
  get 'tags/:skill', to: 'projects#index', as: :skill
  get 'freelancer_skills/:skill', to: 'freelancers#index', as: :freelancer_skill
  get 'my/responses', to: 'responses#index'
  post 'responses/accept', to: 'responses#accept'
  post 'responses/cancel_response', to: 'responses#cancel_response'

  resources :projects do
    collection do
      match 'search' => 'projects#search', via: [:get, :post], as: :search
    end
  end

  mount Judge::Engine => '/judge'

  root 'projects#index'
end

app/views/shared/_aside.html.erb
<% content_for :below_main do %>
  <aside class="column_sidebar">
    <%= content %>
  </aside>
<% end %>

app/views/shared/_avatar_user.html.erb
<div class="avatar_user_panel">
  <%= link_to freelancer_path(current_user.freelancer.friendly_id), class: "user-panel__avatar active" do %>
    <%= avatar_for current_user.freelancer.photo %>
  <% end %>
</div>
<div class="user-panel__side">
  <%= link_to current_user.username, freelancer_path(current_user.freelancer.friendly_id), class: "user-panel__user-name" %>
  <span class="btn_drop icon_arrow_up" role="expand_menu_trigger" onclick="showHide('user_panel__menu_id')"></span>
</div>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
  <h2><%= pluralize(object.errors.count, "error") %> were found:</h2>

  <div class="field_error">
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer class='layout__footer'>
<div class='column_main'>
<div class='page'>
<ul class='menu menu_horizontal menu_footer'>
<li class='menu__item'>
  <%= link_to 'About', about_path, class: "link", data: { turbolinks: false } %>
</li>
<li class='menu__item'>
  <%= link_to 'List of changes', changeslog_path, class: "link", data: { turbolinks: false } %>
</li>
<li class='menu__item'>
  <%= link_to 'Help', help_path, class: "link", data: { turbolinks: false } %>
</li>
<li class='menu__item'>
<%= link_to 'Contact us', feedback_path, class: "link", data: { turbolinks: false } %>
</li>
<li class='menu__item menu__item_right'>
<a class="link" target="_blank" href="#">Text</a>
</li>
</ul>
</div>
</div>
<div class='column_sidebar column_sidebar_footer'>
    <ul class='icons-bar icons-bar_socials'>
        <li class='icons-bar__item'>
          <a class="icons-bar__icon icon_fb" title="Facebook" href="#" data-turbolinks="false"></a>
        </li>
        <li class='icons-bar__item'>
          <a class="icons-bar__icon icon_tw" title="Twitter" href="#" data-turbolinks="false"></a>
        </li>
    </ul>

<div class='copyright'>
&copy;
<a target="_blank" href="#">Freelance-DE</a>
</div>
</div>

<img class='footer__pix' src=''>
</footer>

app/views/shared/_head.html.erb
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="target-densitydpi=device-dpi, width=device-width, minimum-scale=1, initial-scale=1">

<title>FlMarket</title>
<meta content='Freelance-DE' property='og:title'>
<meta content='Freelance-DE – orders for freelancers' property='og:description'>
<meta content='Freelance-DE – orders for freelancer' name='description'>

<link rel="shortcut icon" type="image/x-icon" href="favicon.png" />

app/views/shared/_header.html.erb
<% content_for(:above_main) do %>
  <header class="column_wrap column_header">
    <div class="column_main">
      <h1 class="page-title"><%= text %></h1>
    </div>
    <div class="column_sidebar">
      <% if current_user && !current_user.freelancer.intro %>
        <%= link_to "#{t :new_project}", intro_path, class: 'btn_blue icon_pen' %>
      <% else %>
        <%= link_to "#{t :new_project}", new_project_path, class: 'btn_blue icon_pen' %>
      <% end %>
    </div>
  </header>
<% end %>

app/views/shared/_layout_navbar.html.erb
<aside class='layout__navbar' id='navbar'>
  <div class='logo_wrap'>
    <%= link_to 'FlMarkt', root_path, class:"logo" %>
  </div>
  <div class='tabs tabs_vertical'>
    <div class='tabs__menu'>
      <% if user_signed_in? %>
        <%= render 'shared/user_panel' %>
      <% else %>
        <div class='user-panel' role='user_expand_menu'>
          <div class='user-panel_head user-panel_head_login'>
            <%= link_to "#{t :sign_in}", new_user_session_path, class: "menu__link menu__link_login icon_settings_keys" %>
          </div>
        </div>
      <% end %>
      <ul class='menu'>
        <li class='menu__item'>
          <%= link_to "#{t :orders}", projects_path, class: "menu__link link icon_tasks menu__link_active" %>
        </li>
        <li class='menu__item'>
          <%= link_to 'Freelancers', freelancers_path, class: "menu__link link icon_freelancers" %>
        </li>
      </ul>
      <% unless user_signed_in? %>
        <section class='promo-block promo-block_sticky-bottom'>
          <h3 class='promo-block__title'>Freelance&nbsp;&mdash; <br/> Service for IT </h3>
          <p class='promo-block__desc'>
            Respond to an interesting order or find the artist for the project.
          </p>
          <%= link_to "#{t :sign_up}", new_user_registration_path, class: "btn btn_blue" %>
        </section>
      <% end %>
    </div>
  </div>

</aside>

app/views/shared/_menu_user_settings.html.erb
<ul class="menu menu_user-settings">
  <li class="menu__item">
    <%= link_to t('profile'), @freelancer, class: "menu__link link icon_settings_account"%>
  </li>
  <li class="menu__item">
    <%= link_to "Account", edit_user_registration_path, class: "menu__link link icon_settings_account"%>
  </li>
  <li class="menu__item">
    <a class="menu__link link icon_settings_delivery menu__link_active" href="/"><%= t('subscribe') %></a>
  </li>
</ul>

app/views/shared/_search.html.erb
<div class='search-suggest'>
  <form id="search_items" action="" accept-charset="UTF-8" method="get">
    <input name="utf8" type="hidden" value="&#x2713;" />
    <input type="text" name="q" id="q" size="60" class="search-suggest___field" placeholder="Search..." />
    <i class='search-suggest__icon icon_search'></i>
  </form>
</div>

app/views/shared/_user_panel.html.erb
<div class="user-panel user-panel_expand" role="user_expand_menu">
  <div class="user-panel_head">
    <%= render 'shared/avatar_user' %>
  </div>
  <div class="user-panel__menu" style="height: 240px;"  id="user_panel__menu_id">
    <ul class="menu menu_navbar" role="expand_menu_dropdown">
      <li class="menu__item">
        <%= link_to "#{t :my_orders}", project_user_projects_path, class: "menu__link link icon_tasks" %>
      </li>
      <li class="menu__item">
        <%= link_to "#{t :my_responses}", my_responses_path, class: "menu__link link icon_responses" %>
      </li>
      <li class="menu__item">
        <%= link_to "#{t :settings}", edit_freelancer_path(current_user.freelancer.friendly_id), class: "menu__link icon_settings" %>
      </li>
      <li class="menu__item">
        <%= link_to "#{t :log_out}", destroy_user_session_path, method: :delete, class: "menu__link link icon_logout" %>
      </li>
    </ul>

  </div>
</div>