config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'changeslog', to: 'static_pages#changeslog'
  get 'help', to: 'static_pages#help'
  get 'feedback', to: 'static_pages#feedback'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :locales, only: [:new]


  get 'documents/delete'
  get '/projects/archive'
  get '/projects/show_archive'
  get "portfolios/watch" => 'portfolios#watch', :as => :watch
  get 'projects/accept' => 'projects#accept', :as => :accept
  get 'projects/refuse' => 'projects#refuse', :as => :refuse
  get 'projects/completed' => 'projects#completed', :as => :completed
  get 'projects/accept_intro' => 'projects#accept_intro', :as => :accept_intro
  get 'projects/intro' => 'projects#intro', :as => :intro

  resources :freelancers
  resources :projects do
    resources :responses, expect: :index
  end
  resources :project do
    resources :comments
  end
  resources :responses do
    resources :comments
  end

  resources :intros
  resources :documents
  resources :photos
  resources :portfolios
  resources :backgrounds
  resources :project_transitions
  namespace :project do
    get 'my/tasks', to: 'profile_projects#index', as: :user_projects
  end
  resources :subscribers
  get 'tags/:skill', to: 'projects#index', as: :skill
  get 'freelancer_skills/:skill', to: 'freelancers#index', as: :freelancer_skill
  get 'my/responses', to: 'responses#index'
  post 'responses/accept', to: 'responses#accept'
  post 'responses/cancel_response', to: 'responses#cancel_response'

  resources :projects do
    collection do
      match 'search' => 'projects#search', via: [:get, :post], as: :search
    end
  end

  mount Judge::Engine => '/judge'

  root 'projects#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id             :integer          not null, primary key
#  title          :string
#  description    :text
#  price          :integer
#  location       :string
#  payment        :string
#  anonymity      :boolean
#  category_id    :integer
#  archive        :boolean          default(FALSE)
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  price_category :string
#  user_id        :integer
#  performer_id   :integer
#
# Indexes
#
#  index_projects_on_user_id  (user_id)
#

class Project < ActiveRecord::Base
  include Statesman::Adapters::ActiveRecordQueries

  belongs_to :category
  has_many :documents
  belongs_to :user
  has_many :comments
  has_many :responses
  belongs_to :performer, class_name: 'Freelancer', foreign_key: 'performer_id'
  has_and_belongs_to_many :payment_options
  has_many :project_transitions, autosave: false

  accepts_nested_attributes_for :documents

  validates :title, :description, presence: true
  validates :category_id, presence: true
  validates :payment_option_ids, presence: true
  validates :price, numericality: { only_integer: true, allow_nil: true }

  acts_as_taggable
  acts_as_taggable_on :skills
  include Impressionist::IsImpressionable
  is_impressionable
  #is_impressionable :counter_cache => true
  #scope :by_join_date, order("created_at DESC")

  def state_machine
    @state_machine ||= ProjectStateMachine.new(self, transition_class: ProjectTransition)
  end

  def available
    state_machine.current_state == 'available'
  end

  def in_progress
    state_machine.current_state == 'in_progress'
  end

  def completed
    state_machine.current_state == 'completed'
  end

  def has_performer
    state_machine.current_state == 'has_performer'
  end

  def days_ago
    now = Date.today
    (now - self.created_at.to_date).to_i
  end

  def is_owner?(u)
    self.user_id == u.id
  end

  def set_performer(value=0)

  end

  def remove_performer
    update(performer_id: nil)
  end

  def self.transition_class
    ProjectTransition
  end

  def self.initial_state
    :available
  end
end

app/controllers/project/profile_projects_controller.rb
class Project::ProfileProjectsController < ApplicationController
  def index
    if current_user
      @projects = Project.where(user_id: current_user.id)
      render 'profile_projects/index'
    end
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  require 'will_paginate/array'
  before_action :set_project, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:new, :edit]
  before_action :set_freelancer, only: [:show, :new]
  before_action :set_response_current_user, only: [:show], if: :exist_response?
  after_action :verify_authorized, only: [:update]

  impressionist actions: [:show]

  def index
    if params[:categories]
      @projects = Project.where(category_id: [params[:categories]])
                                  .order("projects.created_at DESC")
                                  .paginate(page: params[:page], per_page: 10)
      render @projects
    elsif params[:skill]
      @projects = Project.tagged_with(params[:skill]).
        paginate(page: params[:page], per_page: 10)
    else
      @q = Project.ransack(params[:q])
      @projects = @q.result(distinct: true)
                    .order("projects.created_at DESC")
                    .paginate(page: params[:page], per_page: 10)
    end

    @categories = Category.all
  end

  def new
    @freelancer.update_attribute :intro, true
    @project = Project.new
    locals payment_options: PaymentOption.all
  end

  def create
    @project = Project.create(project_params)
    if @project.save
      flash[:notice] = 'Your project successfully created.'
      redirect_to @project
    else
      flash[:error] = "Could not save project"
      locals :new, payment_options: PaymentOption.all
    end
  end

  def show
    @new_response = @project.responses.build
  end

  def edit
    if @project.present?
      authorize @project
    else
      skip_authorization
    end
    locals payment_options: PaymentOption.all
  end

  def archive
    @project = Project.find(params[:id])
    if !@project.archive
      @project.update_attribute('archive', true)
      @response = Response.where(project_id: @project.id, freelancer_id: @project.performer_id).first
      if @project.performer.present?
        ResponseMailer.cancel_response(@response).deliver_now
      end
    else
     @project.update_attribute('archive', false)
    end
    redirect_to :back
  end

  def show_archive
    if current_user
      @projects = Project.where(user_id: current_user.id)
      render 'projects/archive'
    end
  end

  def destroy
    @project = Project.find(params[:id])
    if !@project.archive
      @project.update_attribute('archive', true)
    else
     @project.update_attribute('archive', false)
    end
    redirect_to :back
  end

  def update
    if @project.present?
      authorize @project
    else
      skip_authorization
    end
    if @project.update(project_params)
      redirect_to @project
    else
      locals :edit, payment_options: PaymentOption.all
    end
  end

  def search
    index
    render :index
  end

  def category
    @category = Category.find( params[:id])
    @projects = @category.projects.order("projects.created_at DESC")
  end

  def upload_photo
    @project = Project.find(params[:id])
    @document = Document.create(:image => params[:image])
    render :json => { :status => @document.valid? }
  end

  def accept
    @project = Project.find(params[:id])
    @project.state_machine.transition_to(:in_progress)
    respond_to do |format|
      format.js { render 'projects/accept' }
    end
  end

  def refuse
    @project = Project.find(params[:id])
    @project.state_machine.transition_to(:available)
    respond_to do |format|
      format.js { render 'projects/accept' }
    end
  end

  def completed
    @project = Project.find(params[:id])
    @project.state_machine.transition_to(:completed)
    @project.update_attribute('archive', true)
    respond_to do |format|
      format.js { render 'projects/accept' }
    end
  end

  def intro

  end

  private

  def exist_response?
    if user_signed_in?
      Response.exists?(freelancer_id: @freelancer.id, project_id: @project.id)
    else
      false
    end
  end

  def set_freelancer
    @freelancer = Freelancer.find_by(user_id: current_user.id) if user_signed_in?
  end

  def set_project
    @project = Project.find_by(id: params[:id])
  end

  def set_response_current_user
    @response = Response.find_by(project_id: @project.id, freelancer_id: @freelancer.id)
  end

  def project_params
    params.require(:project).permit(:title, :description, :price, :location,
                                    :anonymity, :price_category, :category_id, :user_id, { skill_list: [] },  :skill,
                                    { skill_ids: [] }, :skill_ids, documents_attributes: [:attachment, :_destroy], payment_option_ids: [])
  end
end

app/views/projects/_comments.html.erb
<% @response.comments.each do |comment|%>
  <% if comment.user_id != @response.freelancer_id %>
  <li class="comments-list__item comments-list__item_author">
    <div class="avatar_comment">
      <figure class="user__avatar user__avatar_r50">
        <%= avatar_for @response.project.user.freelancer.photo %>
      </figure>
    </div>
    <div class="comment_wrap">
      <div class="comment">
        <div class="comment__header">
          <%= link_to freelancer_path(comment.user_id), :class => "user__name user__name_link" do%>
            <%= @response.project.user.freelancer.first_name %>
          <%end%>
          <span class="date_publish">
            <%=distance_of_time_in_words(DateTime.now.to_i-comment.created_at.to_i)%> ago
          </span>
        </div>
        <div class="comment__body">
          <%= comment.body %>
        </div>
      </div>
    </div>
  </li>
  <% else %>
  <li class="comments-list__item comments-list__item_freelancer">
    <div class="avatar_comment">
      <figure class="user__avatar user__avatar_r50">
        <%= avatar_for @response.freelancer.photo %>
      </figure>
    </div>
    <div class="comment_wrap">
      <div class="comment">
        <div class="comment__header">
          <%= link_to freelancer_path(comment.user_id), :class => "user__name user__name_link" do%>
            <% @response.freelancer.first_name %>
          <%end%>
          <span class="date_publish">
            <%=distance_of_time_in_words(DateTime.now.to_i-comment.created_at.to_i)%> ago
          </span>
        </div>
        <div class="comment__body">
          <%= comment.body %>
        </div>
      </div>
    </div>
  </li>
  <%end%>
<% end %>

app/views/projects/_document_fields.html.erb
<div class="nested-fields">


  <%= form_for(Document.new, html: { multipart: true, class: "dropzone"}) do |a|  %>
    <div class="fallback">
      <%= f.file_field :attachment %><br>
    </div>
  <% end %>
</div>
<br>

app/views/projects/_new_response.html.erb
<div class="new-response">
  <div class="response-list response-list_tasks">
    <div class="response-list__header">
      <span class="response-list__title">
        Your offer
      </span>
    </div>
    <%= form_for [project, response], remote: true, class: 'form_response' do |f| %> 
      <div class="field">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.submit "Send", class: 'btn_green' %>  
    <% end %>
  </div>
</div>

app/views/projects/_no_vacancies.html.erb
<div class="layout-block layout-block_dark">
  <div class="layout-block__title icon_hantim_alert">
    Freelance for orders
  </div>
  <div class="layout-block__desc">
    Please do not post vacancy in orders.
  </div>
</div>

app/views/projects/_project.html.erb
<% if !project.archive %>
<li class='content-list__item'>
  <article class='task task_list'>
    <div class='task__column_desc'>
      <header class='task__header'>
        <div class='task__title'>
          <%= link_to project.title, project %>
        </div>
        <div class='task__params params'>
                        <span class='params__responses icon_task_responses' title='Number of responses'>
                        <i class='params__count'</i>
                        <%= project.responses.count %>
                        response(s)
                        </span>
                        <span class='params__views icon_task_views' title='Number of views Order this month'>
                        <i class='params__count'><%= project.impressions.count %></i>
                        views
                        </span>
                        <span class='params__published-at icon_task_publish_at' title='Order Date'>
                        ~
                        <%= distance_of_time_in_words(DateTime.now.to_i-project.created_at.to_i) %>
                        </span>
        </div>
      </header>
      <div class='task__tags'>
        <ul class="tags tags_short">
          <% project.skill_counts.each do |skill| %>
            <li class="tags__item">
              <%= link_to skill.name, skill_path(skill.name), class: "tags__item_link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
    <aside class='task__column_price'>
      <div class='task__price'>
        <span class='icon_cash_small' title='Price'></span>
                     <span class='count'>
                        <%= project.price %>
                       <span class="suffix">
                            <%= project.price_category %>
                        </span>
                    </span>

      </div>
    </aside>
  </article>
</li>
<% end %>

app/views/projects/_response.html.erb
<div class="response-list response-list_tasks">
  <ul class="tabs-menu tabs-menu_sub_open" role="tabs">
    <li class="tabs-menu__item" id="tab_all">
      <a class="tabs-menu__link link_active" role="tabs_link" data-remote="true" href="/tasks/142270/task_comments">
        My response
      </a>
    </li>
  </ul>

  <div class="response-list"; id="response-list">
  <ul class="content-list content-list__my-response content-list_responses">
    <% if @response.persisted? %>
      <li class="content-list__item">
        <article class="user user_response">
          <figure class="user__avatar user__avatar_r50">
            <%= avatar_for @response.freelancer.photo %>
          </figure>
          <div class="user__info">
          <header class="user-data">
            <div class="user-data__title">
              <%= link_to "#{@response.freelancer.first_name} #{@response.freelancer.last_name}", @response.freelancer %>
              <span class="user__published_at">
                <%= @response.days_ago %> days ago
              </span>
              <div class="user-data__spec">
                <%= @response.freelancer.specialization %>
              </div>
            </div>
          <div class="user__price">
            <span class="icon_free">
              <span class="count"> <%= @response.freelancer.rate %>euro
                <span class="suffix"><%= @response.freelancer.price_category %></span>
              </span>
            </span>
          </div>

          </header>
            <p class="user__message">
              <%= @response.body %>
            </p>
            <div class="user__tags">
              <ul class="tags tags_short">
                <% @response.freelancer.skill_counts.each do |skill| %>
                  <li class="tags__item">
                    <%= link_to skill.name, freelancer_skill_path(skill.name), class: "tags__item_link" %>
                  </li>
                <% end %>
              </ul>
            </div>
          </div>
        </article>

        <div class="controls">
          <%= link_to "Delete your offer", project_response_path(@project, @response), remote: true, method: :delete,
                                           class: "control control_delete_trash" %>

          <label class="control_check animated fadeOutDown" title="Выбрать исполнителя" data-active="false" data-hidden="false" style="display: none;">
            <input type="checkbox" name="set_executor" id="set_executor" value="true" class="control__check" role="toggler" data-url="http://freelansim.ru/tasks/142270/executor_found.json?authenticity_token=yXmoBcU6tCpw%2F7ggvjXKTg8Y1YDnX6LK%2FU1xualZll6PbYNVLGc0eaFydL%2FTDg7bR8Rs7gD%2FwassRBDpDpmXtQ%3D%3D&amp;datetime=1462619522&amp;login=rsajob" data-should-confirm="true" data-off-confirmer="#off-confirm" data-on-confirmer="#on-confirm" data-confirm-once="false" data-container="label.control_check">
            <span class="control__icon control__icon_performer">Выбрать исполнителя</span>
          </label>

          <%= label_tag "Accepte performer", class: 'control_check animated fadeOutDown' do %>
            <%= check_box_tag "edfdewfdewfdewf", 0, @project.set_performer, class: "control__check" %>
          <% end %>
          <%= link_to "Edit offer", '', class: "control control_edit", id: "control_edit_response", data: { response_id: @response.id } %>
        </div>
      </li>
    <% end %>
    <% if !@response.comments.blank? %>
    <ul class="comments-list">
      <div class="comments-<%=@response.id%>">
          <%= render 'comments' %>
      </div>
    </ul>
    <!-- Form for new comment -->
    <%= form_for [response, Comment.create], :url => response_comments_path(:response_id => @response.id), data: {new_comm_id: @response.id}, remote: true do |f| %>
      <div class="field" id="new-comment">
        <%= f.text_area :body, class: 'form-control' %>
      </div>
      <%= f.hidden_field :user_id, value: current_user.id %>
      <%= f.submit "Send", class: 'btn_green', multipart: true, data: {response_id: @response.id} %>
    <% end %>
    <% end %>
  </ul>
  <%= form_for [@project, @response], remote: true, html: { class: 'form_response', id: "edit-response-#{@response.id}", style: "display:none;"} do |f| %>
    <div class="field">
      <%= f.text_area :body, class: 'form-control' %>
    </div>
    <%= f.submit "Send", class: 'btn_green' %>
  <% end %>
  </div>
</div>

<p><a href="#" class="simple-back-to-top"></a></p>
<script type="text/javascript">
// create the back to top button
  $('body').prepend('<a href="#" class="back-to-top">Back to Top</a>');

  var amountScrolled = 300;

  $(window).scroll(function() {
	   if ( $(window).scrollTop() > amountScrolled ) {
		     $('a.back-to-top').fadeIn('slow');
	   } else {
		     $('a.back-to-top').fadeOut('slow');
	   }
     });
     $('a.back-to-top, a.simple-back-to-top').click(function() {
	      $('html, body').animate({
		        scrollTop: 0
	         }, 700);
	          return false;
    });
</script>

app/views/projects/_state_control.html.erb
<div class="controls">
  <b>Project in status:</b>
  <span class="statesman-<%= @project.state_machine.current_state%>">
    <%= @project.state_machine.current_state %>
  </span>
</div>
<% if current_user == @project.user %>
  <div class='controls' style="top:60px;">
    <% if @project.state_machine.in_state?(:available, :has_performer) %>
      <div class="dropdown">
        <div class="dropbtn" data-dropid="<%=@project.id%>">
          <span class="icon_settings_bordered">
          </span>
        </div>
        <div id="myDropdown-<%=@project.id%>" class="dropdown-content">
                <% if !@project.archive %>
                  <%= link_to "Archive", projects_archive_path(@project, :id => @project.id)%>
                <% else %>
                  <%= link_to "Restore", projects_archive_path(@project, :id => @project.id)%>
                <% end %>
                <%= link_to "Edit", edit_project_path(@project)%>
                <% if !@project.archive %>
                  <%= link_to "Finish", project_path(@project),   method: :delete, data: { confirm: 'Are you sure you want to finish this project?' } %>
                <% end %>
        </div>
      </div>
    <% elsif @project.state_machine.in_state?(:in_progress) %>
      <%= link_to "Complet", completed_path(:id => @project.id), {:remote => true, class: "btn_green"}%>
    <% end %>
  </div>
<% end %>
<% if current_user && current_user.id == @project.performer_id && @project.state_machine.current_state == 'has_performer' %>
  <div class="controls" style="top:60px;" >
    <div>
      <%= link_to "Accept", accept_path(:id => @project.id), {:remote => true, class: "btn_green"}%>
    </div>
    <div style="margin-top:10px">
      <%= link_to "Refuse", refuse_path(:id => @project.id), {:remote => true, class: "btn_red"}%>
    </div>
  </div>
<% end %>

app/views/projects/category.html.erb
<%= header('Orders') %>
<% content_for(:before_main) do %>
  <%= render 'shared/search' %>
<% end %>

<ul class='content-list content-list_tasks' id='tasks_list'>
  <%= render @projects %>
</ul>

<div id='pagination'>
  <div class="pagination">

  </div>
</div>

<% aside render('categories/categories') %>

app/views/projects/edit.html.erb
<%= header('Place order') %>

<%= form_for @project, class: "form_standart form_add-task no_ctrl_enter_submit" do |f| %>
  <%= render 'shared/errors', object: @project %>

  <ul class="form-fields form-fields_nested">
    <li class="form-fields__group form-fields__group_full">
      <%= f.label 'Name' do %>
        Name
        <span class="required">*</span>
      <% end %>
      <div class="field">
        <%= f.text_field :title, class: 'form-control' do %>
          <small class="field__counter">70</small>
        <% end %>
      </div>
    </li>
    <li class="form-fields__group">
      <%= f.label 'Price' %>
      <div class="field field_type-money">
                <span class="field_money">
                  <%= f.text_field :price, class: 'form-control form-control_small form-control_money money_format' do  %>
                    <small class="field__counter">8</small>
                  <% end %>
                  <span class="field__postfix">euro.</span>
                  <input type="hidden" name="money_error" id="task_money" value="">
                </span>
        <span>for</span>
        <div class="form-control_select">
          <%= f.select :price_category, price_category_options, {}, { class: "form-control"} %>
        </div>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full">
      <%= f.label :description do %>
        Description:
        <span class="required">*</span>
      <% end %>
      <div class="field">
        <%= f.cktext_area :description, id:"ckeditor", :"data-no-turbolink" => true, ckeditor: { toolbar: 'mini'} %>
      </div>
      <script>
        CKEDITOR.replace('ckeditor');
      </script>

    </li>
    <li class="form-fields__group">
      <%= f.label 'Category' do %>
        Category
        <span class="required">*</span>
      <% end %>
      <div class="menu " id="selector_links">
        <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: 'form-control'} %>
      </div>

    </li>
    <li class="form-fields__group form-fields__group_full">
      <label>
        Skills Freelancer (15 pieces)
      </label>

      <div class='field'>
        <%= f.select :skill_list, @project.skills.all, { class: "form-control" }, multiple: true, class: "form-control", style: 'width: 100%' %>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full">
      <%= f.label 'City' %>
      <div class="field">
        <% if @project.location.blank? %>
          <%= f.select :location, [], {}, style: 'width: 100%;', multiple: true, class: 'select_location form-control' %>
        <% else %>
          <%= f.select :location, @project.location, {}, style: 'width: 100%;', multiple: true, class: 'select_location form-control' %>
        <% end %>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full">
      <%= f.label 'Possible payment method' do %>
        Possible payment methods
        <span class="required">*</span>
      <% end %>

      <div class="field">
        <%= collection_check_boxes :project, :payment_option_ids, PaymentOption.all, :id, :name do |t| %>
          <label class="checkbox checkbox_flat">
            <%= t.check_box %>
            <span class="checkbox__label">
                      <%= t.text %>
                    </span>
          </label>
        <% end %>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full", style="display: none;">
      <%= f.label 'Anonymity order' %>
      <div class="field field_checkbox">
        <div class="field__help">
          Setup allows for contractors to remain anonymous. Note that this may reduce the number of responses
        </div>
      </div>
      <label class="checkbox checkbox_flat">
        <%= f.check_box :anonymity %>
        <span class="checkbox__label">
                Place Order anonymously
              </span>
      </label>
    </li>
    <li class="form-fields__group" id="task_anyfile_ids_hidden"></li>



  <li class="form-fields__group form-fields__group_full">
  <div class='form_standart'>
    <label for="anyfile_item">Files</label>
    <div class="form-fields__group form-fields__group_full" id="doc_for_project"  data-docid="<%=@project.id%>">
      <%= link_to_add_association 'add file', f, :documents, class: "add_assotiation", id: "link_to_association"%>
    </div>
    <ul class="files-list files-list_form">
      <% @project.documents.each do |document| %>
        <li class="files-list__item files-list__item_success" id="<%= dom_id(document) %>">
          <div class="files-list__show"></div>
          <%= link_to document.attachment.name, document.attachment.url, class: 'files-list__link' %>
          <%= link_to "Delete", document_path(document), class: 'files-list__delete', remote: true,  method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
        </li>
      <% end %>
    </ul>
  </div>
  </li>
  </ul>
  <div class="form-fields__group_buttons">
    <%= f.submit 'Save', class: 'btn_green' %>
  </div>
<% end %>
<% aside render('no_vacancies') %>

app/views/projects/index.html.erb
<%= header('Orders') %>

<% content_for(:before_main) do %>
  <div class='search-suggest'>
    <%= search_form_for @q, url: search_projects_path, html: { method: :post } do |f| %>
      <%= f.search_field :title_or_description_or_skills_name_cont, class: "search-suggest___field", placeholder: "Search..." %>
      <i class='search-suggest__icon icon_search'></i>
      <%= f.submit "Search" %>
    <% end %>
  </div>
<% end %>

<ul class='content-list content-list_tasks' id='tasks_list' remote="true">
  <%= render @projects %>
</ul>
<div id='pagination'>
  <div class="pagination">
    <%= will_paginate @projects %>
  </div>
</div>
<% aside render('categories/categories') %>

app/views/projects/intro.html.erb
<div class="advices">
  <h2 class="task_title"><%= t('before_create_project')%></h2>

  <div class="advice">
    <label for="a1" class="checkbox checkbox_flat">
      <input type="checkbox" value="1" id="a1" class="advice_check">
      <span class="checkbox__label">
        <%= t('label_1')%>
      </span>
    </label>
    <div class="clear"></div>
    <label for="a1" class="text">
      <%= t('description_1') %><br><br>
      <strong class="false"><%= t('bad_practice')%></strong>
      <em><%= t('bad_practice_1')%></em><br><br>
      <strong class="true"><%= t('good_practice')%></strong>
      <em><%= t('good_practice_1')%></em><br><br>
    </label>
  </div>

  <div class="advice disabled">
    <label for="a2" class="checkbox checkbox_flat">
      <input type="checkbox" value="2" id="a2" class="advice_check" disabled="true">
      <span class="checkbox__label">
        <%= t('label_2')%>
      </span>
    </label>
    <div class="clear"></div>
    <label for="a2" class="text">
      <%= t('description_2') %><br><br>
      <strong class="false"><%= t('bad_practice')%></strong>
      <em><%= t('bad_practice_2')%></em><br><br>
      <strong class="true"><%= t('good_practice')%></strong>
      <em><%= t('good_practice_2')%></em><br><br>
    </label>
  </div>

  <div class="advice disabled">
    <label for="a3" class="checkbox checkbox_flat">
      <input type="checkbox" value="3" id="a3" class="advice_check" disabled="true">
      <span class="checkbox__label">
        <%= t('label_3')%>
      </span>
    </label>
    <div class="clear"></div>
    <label for="a3" class="text">
      <%= t('description_3') %><br><br>
    </label>
  </div>

  <div class="advice disabled">
    <label for="a4" class="checkbox checkbox_flat">
      <input type="checkbox" value="4" id="a4" class="advice_check" disabled="true">
      <span class="checkbox__label">
        <%= t('label_4')%>
      </span>
    </label>
    <div class="clear"></div>
    <label for="a4" class="text">
      <%= t('description_4') %><br><br>
      <strong class="false"><%= t('bad_practice')%></strong>
      <em><%= t('bad_practice_4')%></em><br><br>
      <strong class="true"><%= t('good_practice')%></strong>
      <em><%= t('good_practice_4')%></em><br><br>
    </label>
  </div>

  <div class="advice disabled">
    <label for="a5" class="checkbox checkbox_flat">
      <input type="checkbox" value="5" id="a5" class="advice_check" disabled="true">
      <span class="checkbox__label">
        <%= t('label_5')%>
      </span>
    </label>
    <div class="clear"></div>
    <label for="a5" class="text">
      <%= t('description_5') %><br><br>
    </label>
  </div>

  <div class="form-fields__group_buttons">
    <%= button_to "Submit", new_project_path, method: 'get', class: 'btn_green', disabled: true, id: 'advice_check_button' %>
  </div>

</div>
<% aside render('shared/menu_user_settings') %>