config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'changeslog', to: 'static_pages#changeslog'
  get 'help', to: 'static_pages#help'
  get 'feedback', to: 'static_pages#feedback'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :locales, only: [:new]


  get 'documents/delete'
  get '/projects/archive'
  get '/projects/show_archive'
  get "portfolios/watch" => 'portfolios#watch', :as => :watch
  get 'projects/accept' => 'projects#accept', :as => :accept
  get 'projects/refuse' => 'projects#refuse', :as => :refuse
  get 'projects/completed' => 'projects#completed', :as => :completed
  get 'projects/accept_intro' => 'projects#accept_intro', :as => :accept_intro
  get 'projects/intro' => 'projects#intro', :as => :intro

  resources :freelancers
  resources :projects do
    resources :responses, expect: :index
  end
  resources :project do
    resources :comments
  end
  resources :responses do
    resources :comments
  end

  resources :intros
  resources :documents
  resources :photos
  resources :portfolios
  resources :backgrounds
  resources :project_transitions
  namespace :project do
    get 'my/tasks', to: 'profile_projects#index', as: :user_projects
  end
  resources :subscribers
  get 'tags/:skill', to: 'projects#index', as: :skill
  get 'freelancer_skills/:skill', to: 'freelancers#index', as: :freelancer_skill
  get 'my/responses', to: 'responses#index'
  post 'responses/accept', to: 'responses#accept'
  post 'responses/cancel_response', to: 'responses#cancel_response'

  resources :projects do
    collection do
      match 'search' => 'projects#search', via: [:get, :post], as: :search
    end
  end

  mount Judge::Engine => '/judge'

  root 'projects#index'
end

app/models/freelancer.rb
# == Schema Information
#
# Table name: freelancers
#
#  id             :integer          not null, primary key
#  first_name     :string
#  last_name      :string
#  rate           :integer
#  birthday       :string
#  location       :string
#  description    :text
#  site           :string
#  visible        :boolean
#  category_id    :integer
#  created_at     :datetime         not null
#  updated_at     :datetime         not null
#  user_id        :integer
#  specialization :string
#  price_category :string
#  ownership      :string
#  email          :string
#  phone          :string
#  experience     :string
#  username       :string
#  slug           :string
#  intro          :boolean          default(FALSE)
#
# Indexes
#
#  index_freelancers_on_category_id  (category_id)
#  index_freelancers_on_slug         (slug) UNIQUE
#  index_freelancers_on_user_id      (user_id)
#

class Freelancer < ApplicationRecord
  extend FriendlyId
  friendly_id :username, use: :slugged
  belongs_to :category
  belongs_to :user
  has_many :links
  has_many :responses
  has_one :photo
  has_one :background
  has_many :projects, foreign_key: 'performer_id'
  has_many :portfolios
  has_and_belongs_to_many :payment_options, join_table: :payment_options_freelancers
  has_and_belongs_to_many :ownership_types, join_table: :ownership_types_freelancers
  # validates :first_name, :last_name, :description, :specialization, :payment_option_ids, presence: true
  # validates :rate, numericality: { only_integer: true, allow_nil: true }

  accepts_nested_attributes_for :links, allow_destroy: true

  acts_as_taggable
  acts_as_taggable_on :skills

  PRICE_CATEGORIES = [:project, :hour, :month, :for_1000_chars]
  WORK_EXPERIENCE = [:less_than_year, :more_than_year, :more_than_3_years, :more_than_5_years, :more_than_10_years]

  def age
    now = Time.now.utc.to_date
    birthday_date_type = Date.strptime(self.birthday, '%m/%d/%Y')
    now.year - birthday_date_type.year - ((now.month > birthday_date_type.month || (now.month == birthday_date_type.month && now.day >= birthday_date_type.day)) ? 0 : 1 )
  end
end

app/controllers/freelancers_controller.rb
class FreelancersController < ApplicationController
  before_action :set_freelancer, only: [:show, :edit, :update]
  before_action :set_variables, only: [:show, :edit, :update]
  before_action :authenticate_user!, only: [:edit]

  after_action :verify_authorized, only: [:update]

  def index
    if params[:skill]
      @freelancers = Freelancer.tagged_with(params[:skill]).paginate(page: params[:page], per_page: 10)
    else
      @freelancers = Freelancer.all.paginate(page: params[:page], per_page: 10)
    end
    @categories = Category.all
  end

  def show
  end

  def edit
    if @freelancer.present?
      authorize @freelancer
    else
      skip_authorization
    end
  end

  def update
    if @freelancer.present?
      authorize @freelancer
    else
      skip_authorization
    end
    redirect_to @freelancer if @freelancer.update(freelancer_params)
  end

  private

  def freelancer_params
    params.require(:freelancer).permit(:first_name, :last_name, :rate, :birthday,
                                       :location,  :description, :site, :visible, :avatar, :specialization, :price_category,
                                       :ownership, :email, :phone, :experience, :skill_list, { skill_list: [] }, :skill, { skill_ids: [] }, :skill_ids, :category_id,
                                       links_attributes: [:id, :url, :messenger_type_id, :_destroy], payment_option_ids: [], ownership_type_ids: [])
  end

  def set_freelancer
    @freelancer = Freelancer.friendly.find(params[:id])
  end

  def set_variables
    @photo = @freelancer.photo
    @background = @freelancer.background
    @ownership_types = OwnershipType.all
    @payment_options = PaymentOption.all
  end

end

app/helpers/freelancers_helper.rb
module FreelancersHelper
  def work_experience_options
    Freelancer::WORK_EXPERIENCE.map {|val| [t("dropdowns.work_experience.#{val}"), val] }
  end
end

app/views/freelancers/_add_portfolio.html.erb
<%= form_for(Portfolio.new, html: { id: 'modal', remote: true, turbolinks: false}) do |f|  %>
  <%= f.hidden_field :freelancer_id, value: @freelancer.id %>
<!-- The Modal -->
<div id="myModal" class="modal-portfolio">
  <!-- Modal content -->
  <div class="modal-content">
    <div class="modal-header">
      <span class="close">×</span>
      <h2>My projects</h2>
    </div>
    <div class="modal-body">
        <table id="doc_for_portfolio" data-docid="">
          <tr class="table__row">
            <td>
            <label>Project title</label>
            <%= f.text_field :title, validate: true, class: 'form-control' do %>
              <small class="field__counter">70</small>
            <% end %>
            </td>
            <td>
              <label>Category</label>
              <div class="menu " id="selector_links">
                <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: 'form-control'} %>
              </div>
            </td>
          </tr>
          <tr class="table__row">
            <td>
              <label>Project URL</label>
              <%= f.text_field :project_url, validate: false, class: 'form-control'%>
            </td>
            <td>
              <label>Completion date</label>
              <%= f.text_field :completion_date, class: 'birthday1 form-control' %>
            </td>
          </tr>
        </table>
        <table>
          <tr class="table__row">
            <td>
              <%= f.label :description do %>
                Description:
                <span class="required">*</span>
              <% end %>
              <div class="field">
                <%= f.cktext_area :description, :"data-no-turbolink" => true, id: 'ckeditor_modal', ckeditor: { toolbar: 'mini', height: '200px'} %>
              </div>
              <script>
                CKEDITOR.replace('ckeditor_modal');
              </script>
            </td>
          </tr>
          <tr class="table__row">
            <td>
              <div>
                <%= link_to_add_association 'add file', f, :documents, class: "add_assotiation", id: "link_to_association"%>
              </div>
            </td>
          </tr>
            <!-- <td>
            <label>Skill</label>
            <%= f.select :skill_list, {}, { class: "form-con" }, multiple: true, style: 'width: 100%', class: "form-con" %>
          </td> -->
        </table>
          <!-- <div class="field">
            <label>Was this project done on FLmarkt?</label>
          </div> -->
    </div>
    <div class="modal-footer">
      <div class="form-fields" id="btn_modal">
        <%= f.submit 'Publish project', class: 'btn_green', id: 'create',  data: { turbolinks: false }%>
        <button class="btn_red" id="cancel" >Cancel</button>

      </div>
    </div>
  </div>
</div>
<% end %>

app/views/freelancers/_document_fields.html.erb
<div class="nested-fields">
  <label>File (first file using for preview)</label>

  <%= form_for(Document.new, html: { multipart: true, class: "dropzone"}) do |a|  %>
    <div class="fallback">
      <%= f.file_field :attachment %>
    </div>
  <% end %>
</div>
<br>

app/views/freelancers/_form.html.erb
<%= form_for @freelancer, class: "form_standart" do |f| %>
  <ul class="form-fields">
    <li class="form-fields__group form-fields__group_full">
      <label for="freelancer_first_name"><%= I18n.t 'activerecord.attributes.freelancer.first_name' %></label>
      <div class="field">
        <%= f.text_field :first_name, class: "form-control" %>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full">
      <label for="freelancer_first_name"><%= I18n.t 'activerecord.attributes.freelancer.last_name' %></span></label>
      <div class="field">
        <%= f.text_field :last_name, class: "form-control" %>
      </div>
    </li>

    <li class="form-fields__group form-fields__group_full">
      <%= f.label :rate %>
      <div class="field field_type-money">
        <div class="field_money">
          <%= f.text_field :rate, class: "form-control form-control_money money_format" %>
          <span class="field__postfix">euro</span>
        </div>
        <span><%= t('for') %></span>
        <div class="form-control_select">
          <div class="form-control_select">
            <%= f.select :price_category, price_category_options, {}, { class: "form-control" } %>
          </div>
        </div>
      </div>
    </li>

<div id="modal-window"></div>

    <li class="form-fields__group form-fields__group_full">
      <%= f.label :payment_options do %>
        <%= I18n.t('possible_payment_methods') %>
        <span class="required">*</span>
      <% end %>

      <div class="field">
        <%= collection_check_boxes(:freelancer, :payment_option_ids, PaymentOption.all, :id, :name) do |b| %>
          <%= b.label class: "checkbox checkbox_flat" do %>
            <%= b.check_box %>
            <div class="checkbox__label">
              <%= b.text %>
            </div>
          <% end %>
        <% end %>
      </div>
    </li>

    <li>
      <%= f.label :birthday %>
      <div>
        <%= f.text_field :birthday, class: 'birthday1 form-control' %>
      </div>
    </li>

    <li class="form-fields__group form-fields__group_full">
      <%= f.label :location %>
      <div class="field">
        <% if @freelancer.location.blank? %>
          <%= f.select :location, [], {}, style: 'width: 100%;', multiple: true, class: 'select_location form-control' %>
        <% else %>
          <%= f.select :location, @freelancer.location, {}, style: 'width: 100%;', multiple: true, class: 'select_location form-control' %>
        <% end %>
      </div>
    </li>
    <li class="form-fields__group form-fields__group_full">
      <%= f.label :description %>
      <div class="field">
        <%= f.cktext_area :description, :"data-no-turbolink" => true, id: 'ckeditor', ckeditor: { toolbar: 'mini'} %>
      </div>
      <script>
        CKEDITOR.replace('ckeditor');
      </script>
    </li>
  </ul>

  <fieldset class="form-section">
    <legend class="form-section__title form-section__title_border">Portfolio
      <a class="custom_icon link_add-field icon_add_field add_nested_fields" id="myBtn" data-turbolinks="false" ></a>
    </legend>
    <div class="portfolio-container">
      <%= render 'portfolio' %>
    </div>
  </fieldset>

  <fieldset class="form-section">
    <legend class="form-section__title form-section__title_border">
      <%= t('professional_data') %>
    </legend>
    <ul class="form-fields form-fields_reset_top">
      <li class="form-fields__group form-fields__group_full">
        <%= f.label :specialization do %>
          <%= t('specialization') %>
          <span class="required">*</span></label>
        <% end %>
        <div class="field">
          <%= f.text_field :specialization, class: "form-control" %>
        </div>
      </li>

      <li class="form-fields__group form-fields__group_full">
        <label>
          <%= t('professional_skills') %><span class="required">*</span>
        </label>
        <div class='field'>
          <%= f.select :skill_list, @freelancer.skills.all, { class: "form-control" }, multiple: true, class: "form-control", style: 'width: 100%' %>
        </div>
      </li>

      <li class="form-fields__group form-fields__group_full">
        <%= f.label :experience do %>
          <%= t('experience') %> 
          <span class="required">*</span>
        <% end %>
        <!-- <div class="form-control_select">
          <div class="form-control_select"> -->
            <%= f.select :experience, work_experience_options, {}, { class: "form-control" } %>
          <!-- </div> -->
        <!-- </div> -->
      </li>

      <li class="form-fields__group form-fields__group_full">
        <%= f.label :category do %>
          <%= t('provided_service') %>
          <span class="required">*</span>
        <% end %>
        <div class="menu" id="selector_links">
          <%= f.collection_select :category_id, Category.all, :id, :name, {}, { class: 'form-control'} %>
        </div>
      </li>

      <li class="form-fields__group">

        <label><%= t('ownership_type') %></label>
        <div class="field">
          <%= collection_check_boxes(:freelancer, :ownership_type_ids, OwnershipType.all, :id, :title) do |b| %>
            <%= b.label class: "checkbox checkbox_flat" do %>
              <%= b.check_box %>
              <div class="checkbox__label">
                <%= b.text %>
              </div>
            <% end %>
          <% end %>

        </div>
      </li>
    </ul>
  </fieldset>

  <fieldset class="form-section">
    <legend class="form-section__title form-section__title_border"><%= t('contact_information') %></legend>
    <ul class="form-fields form-fields_reset_top">
      <li class="form-fields__group">
        <label for="freelancer_home_page"><%= t('home_page') %></label>
        <div class="field">
          <%= f.text_field :site, class: "form-control" %>
        </div>
      </li>
      <li class="form-fields__group">
        <label for="freelancer_home_page"><%= t('phone') %></label>
        <div class="field">
          <%= f.text_field :phone, class: "form-control" %>
        </div>
      </li>
      <li class="form-fields__group">
        <label for="freelancer_home_page">Email</label>
        <div class="field">
          <%= f.text_field :email, class: "form-control" %>
        </div>
      </li>
    </ul>
  </fieldset>
  <fieldset class="form-section">
    <legend class="form-section__title form-section__title_border"><%= t('i_have') %></legend>
    <div class="form-fields form-fields_reset_top">
      <div class="form-fields__group form-fields__group_ihave">
        <%= f.fields_for :links do |link| %>
          <%= render 'link_fields',  f: link %>
        <% end %>

        <%= link_to_add_association 'Add', f, :links, :data => {:"association-insertion-method" => "prepend"},
                                    class: "custom_icon link_add-field icon_add_field add_nested_fields", style: "padding-top:20px; height:55px" %>
      </div>
      <div class="form-fields__group2">
        <label class="checkbox checkbox_flat">
          <%= f.check_box :visible %>
          <span class="checkbox__label">
            Show my profile in the general list of freelancers
          </span>
        </label>
      </div>
    </div>
  </fieldset>

  <div class="form-fields__group_buttons">
    <%= button_tag 'Cancel', type: :reset, class: "btn_grey" %>
    <%= f.submit 'Publish', class: "btn_green" %>
  </div>
<% end %>

app/views/freelancers/_freelancer.html.erb
<% if freelancer.visible %>
<li class='content-list__item'>
  <article class="user user_short">
    <figure class="user__avatar user__avatar_r50">
      <%= link_to freelancer_path(freelancer) do %>
        <%= avatar_for freelancer.photo %>
      <% end %>
    </figure>
    <div class="user__info">
      <header class="user-data">
        <div class="user-data__title">
          <%= link_to "#{freelancer.first_name} #{freelancer.last_name}", freelancer %>
          <div class="user-data__spec">
            <%= freelancer.specialization %>
          </div>
        </div>
        <div class="user__price" id="freelancer_status_7972">
          <span class="custom_icon icon_relative icon_free" title="Freelancer is free"></span>
            <span class="count"> from <%= freelancer.rate %> euro.<span class="suffix">for <%= freelancer.price_category %></span></span>

        </div>

      </header>
      <p class="user__description">
        <%= simple_format(freelancer.description) %>
      </p>
      <div id="modal-window"></div>
      <% for i in 0..2 %>
      <% if !freelancer.portfolios.offset(i).blank? %>
        <% flag = freelancer.portfolios.offset(i).last.id %>
        <% if current_user && freelancer.user_id == current_user.id %>
          <div class="portfolio" style="display:inline-flex; margin-top:0px">
            <div class="portfolio-items-show">
              <div class="preview-img-show">
                <div class="portfolio-menu-show">
                  <p>
                    <b><%= freelancer.portfolios.find(flag).title %></b>
                  </p>
                  <%= link_to "", watch_path(@portfolio, :id => freelancer.portfolios.find(flag).id), {:remote => true, 'data-target' => '#modal-window', class: "show-portfolio"}%>
                  <%= link_to '', edit_portfolio_path(@portfolio, :id => freelancer.portfolios.find(flag).id),  {:remote => true, 'data-target' => '#modal-window', class: "edit-portfolio"}  %>
                  <%= link_to "", portfolio_path(@portfolio, :id => freelancer.portfolios.find(flag).id), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: "delete-portfolio"%>
                </div>
                <% if freelancer.portfolios.find(flag).documents.count !=0 %>
                  <div class="img_for_portfolio-show" style="background-image: url(<%= freelancer.portfolios.find(flag).documents.first.attachment.url %>)">
                <% end %>
              </div>
            </div>
          </div>
        </div>
        <% else %>
          <%= link_to watch_path(@portfolio, :id => freelancer.portfolios.find(flag).id), {:remote => true, 'data-target' => '#modal-window', class: "link-portfolio"} do%>
            <div class="portfolio" style="display:inline-flex; margin-top:0px">
              <div class="portfolio-items-show">
                <div class="preview-img-show">
                  <div class="portfolio-menu-show">
                    <p>
                      <b><%= freelancer.portfolios.find(flag).title %></b>
                    </p>
                    <%= simple_format truncate(freelancer.portfolios.find(flag).description, escape: false, length: 80) %>
                  </div>
                  <% if freelancer.portfolios.find(flag).documents.count !=0 %>
                    <div class="img_for_portfolio-show" style="background-image: url(<%= freelancer.portfolios.find(flag).documents.first.attachment.url %>)">
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <% end %>
        <% end %>
      <% end %>
      <% end %>
      <div class="user__tags">
        <ul class="tags tags_short">
          <% freelancer.skill_counts.each do |skill| %>
            <li class="tags__item">
              <%= link_to skill.name, freelancer_skill_path(skill.name), class: "tags__item_link" %>
            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </article>
</li>
<% end %>

app/views/freelancers/_link_fields.html.erb
<div class="nested-fields">
  <div class="nested_container">
    <div class="_nested_box">
      <div class="form-control_select">
        <%= f.collection_select :messenger_type_id, MessengerType.all, :id, :title, {}, { class: "form-control" } %>
      </div>
      <div class="field_money" style="margin-left:20px; margin-right:20px">
        <%= f.text_field :url, class: "form-control" %>
      </div>
      <%= link_to_remove_association "Delete", f, class: 'custom_icon icon_remove_field' %>
    </div>
  </div>
</div>

app/views/freelancers/_photo_form.html.erb
<div class="form_user-banner">
  <%= form_for @background, url: {controller: 'backgrounds', action: 'update'}, html: { class: "form_background" } do |a| %>
  <%= a.hidden_field :id, value: @background.id %>
  <div class="field user-banner_upload">
    <%= render partial: 'backgrounds/banner' %>
  </div>
      <div class="btn-group">
        <div class="btn_bordered btn_banner">
          <%= a.file_field :banner, required: true, name: "background[banner]" %>
          <span>Load banner</span>
        </div>
        <%= link_to "Remove", background_path(@background.id),
                    class: 'custom_icon control control_delete_rounded', remote: true, method: :delete, style: 'width:36px;' %>
      </div>
  <% end %>

  <%= form_for @photo, url: {controller: 'photos', action: 'update'},
               html: { class: "form_avatar" } do |f| %>
    <div class="field user-avatar_upload">
      <%= render partial: 'photos/photo' %>
    </div>
    <%= f.hidden_field :id, value: @photo.id %>
    <div class="btn-group_avatar">
      <div class="btn_bordered">
        <%= f.file_field :avatar, required: true, name: 'photo[avatar]' %>
        <span><%= t('load_avatar') %></span>
      </div>
      <%= link_to "Remove", photo_path(@photo.id),
                  class: 'custom_icon control control_delete_rounded', remote: true, method: :delete %>
    </div>
    <div class="form__description">Format: jpg, jpeg, gif, png.<br><%= t('max_size')%> 512kb.</div>
  <% end %>
</div>

app/views/freelancers/_portfolio.html.erb
<% @freelancer.portfolios.each do |portfolio|%>
  <div class="portfolio">
    <div class="portfolio-items">
      <div class="preview-img">
        <div class="portfolio-menu">
          <h6>
            <%= portfolio.title %>
          </h6>
            <div class="portfolio-control">
              <!-- <a class="show-portfolio", id="myBtn" turbolinks="false"></a> -->
              <%= link_to "", watch_path(@portfolio, :id => portfolio.id), {:remote => true, 'data-target' => '#modal-window', class: "show-portfolio"}%>
              <%= link_to '', edit_portfolio_path(@portfolio, :id => portfolio.id),  {:remote => true, 'data-target' => '#modal-window', class: "edit-portfolio"}  %>
              <%= link_to "", portfolio_path(@portfolio, :id => portfolio.id), method: :delete, data: { confirm: 'Are you sure you want to delete this project?' }, class: "delete-portfolio"%>
            </div>
        </div>
        <% if portfolio.documents.count !=0 %>
          <div class="img_for_portfolio" style="background-image: url(<%= portfolio.documents.first.attachment.url %>)">

          </div>
        <% end %>

      </div>
    </div>
  </div>
<% end %>

app/views/freelancers/edit.html.erb
<% header(t('setting_profile')) %>

<%= render 'photo_form' %>

<%= render 'form' %>

<% aside render('shared/menu_user_settings') %>

<%= render 'add_portfolio' %>

app/views/freelancers/index.html.erb
<%= header('Freelancers') %>
<% content_for(:before_main) { render 'shared/search' } %>

<ul class='content-list content-list_freelancers' id='freelancers_list'>
  <% if current_user.nil? %>
    <%= render "projects/require_auth" %>
  <% else %>
    <%= render @freelancers %>
  <% end %>  
</ul>

<div id='pagination'>
  <div class="pagination">
    <%= will_paginate @freelancers %>
  </div>
</div>

<% aside render('shared/menu_user_settings') %>

app/views/freelancers/show.html.erb
<%= header(link_to "All freelancers", freelancers_path, class: "page-title_back") %>

<div class="user-profile profile-blocks">
  <%= render 'freelancers/info/short' %>

  <%= render 'freelancers/info/full' %>
</div>

<% aside render('shared/menu_user_settings') %>