config/routes.rb
Rails.application.routes.draw do
  get 'about', to: 'static_pages#about'
  get 'changeslog', to: 'static_pages#changeslog'
  get 'help', to: 'static_pages#help'
  get 'feedback', to: 'static_pages#feedback'

  devise_for :users, controllers: { omniauth_callbacks: 'omniauth_callbacks' }

  resources :locales, only: [:new]


  get 'documents/delete'
  get '/projects/archive'
  get '/projects/show_archive'
  get "portfolios/watch" => 'portfolios#watch', :as => :watch
  get 'projects/accept' => 'projects#accept', :as => :accept
  get 'projects/refuse' => 'projects#refuse', :as => :refuse
  get 'projects/completed' => 'projects#completed', :as => :completed
  get 'projects/accept_intro' => 'projects#accept_intro', :as => :accept_intro
  get 'projects/intro' => 'projects#intro', :as => :intro

  resources :freelancers
  resources :projects do
    resources :responses, expect: :index
  end
  resources :project do
    resources :comments
  end
  resources :responses do
    resources :comments
  end

  resources :intros
  resources :documents
  resources :photos
  resources :portfolios
  resources :backgrounds
  resources :project_transitions
  namespace :project do
    get 'my/tasks', to: 'profile_projects#index', as: :user_projects
  end
  resources :subscribers
  get 'tags/:skill', to: 'projects#index', as: :skill
  get 'freelancer_skills/:skill', to: 'freelancers#index', as: :freelancer_skill
  get 'my/responses', to: 'responses#index'
  post 'responses/accept', to: 'responses#accept'
  post 'responses/cancel_response', to: 'responses#cancel_response'

  resources :projects do
    collection do
      match 'search' => 'projects#search', via: [:get, :post], as: :search
    end
  end

  mount Judge::Engine => '/judge'

  root 'projects#index'
end

app/models/category.rb
# == Schema Information
#
# Table name: categories
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Category < ActiveRecord::Base
  has_many :projects
  has_many :freelancers
  has_and_belongs_to_many :subscribers, join_table: :categories_subscribers
end

app/views/categories/_categories.html.erb
<dl class='layout-block layout-block_categories'>
  <dt class='layout-block__title'>Categories</dt>
  <dd class='layout-block__content'>
    <ul class='category-group'>
      <!-- <%= render @categories %> -->
      <%= collection_check_boxes :project, :category, Category.all, :id, :name do |b| %>
        <%= b.label class: "checkbox checkbox_flat", remote: true do %>
          <%= b.check_box class: "select-checkbox", remote: true %>
            <span class="checkbox__label">
              <%= b.text %>
            </span>
        <% end %>
      <% end %>
    </form>
    </ul>
  </dd>
</dl>
<dl class='layout-block layout-block_subscribe'>
  <dt class='layout-block__title'>Newsletter</dt>
  <dd class='layout-block__content'>
    Apply for delivery of new orders in your inbox
    <div class='subscribe__button'>
      <% if user_signed_in? %>
        <%= link_to 'Subscribe', edit_subscriber_path(current_user.subscriber), class: "btn_red" %>
      <% else %>
        <%= link_to 'Subscribe', new_user_session_path, class: "btn_red" %>
      <% end %>
    </div>
    <div class='about2'>
      <strong>
        15200+
      </strong>
      freelancers follow the<br>new orders
    </div>
  </dd>
</dl>

app/views/categories/_category.html.erb
<li class='category-group__folder'>
  <div class='category-group__name checkbox_flat'>
    <div class='checkbox_pseudo js-checkbox_group'></div>
    <span class='link_dotted js-toggle'>
      <%= link_to category.name, projects_path(category: category)  %>
    </span>
  </div>
</li>